"""initial_migration

Revision ID: 8fcd2e63a00c
Revises: 
Create Date: 2026-07-12 13:11:06.399017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fcd2e63a00c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulance_fleet',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicle_num', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('insurance_expiry', sa.String(), nullable=False),
    sa.Column('last_service_date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_inventory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('blood_group', sa.String(), nullable=False),
    sa.Column('component', sa.String(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('expiry', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reported_by', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('head_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['head_id'], ['staff_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_service_date', sa.String(), nullable=False),
    sa.Column('maintenance_due', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('blood_group', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('donation_date', sa.DateTime(), nullable=False),
    sa.Column('eligibility', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drug_inventory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('expiry', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('batch', sa.String(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_reagents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('expiry', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dob', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('blood_group', sa.String(), nullable=False),
    sa.Column('emergency', sa.String(), nullable=False),
    sa.Column('insurance', sa.String(), nullable=False),
    sa.Column('abha_id', sa.String(), nullable=True),
    sa.Column('consent_academic', sa.Boolean(), nullable=False),
    sa.Column('consent_commercial', sa.Boolean(), nullable=False),
    sa.Column('consent_future', sa.Boolean(), nullable=False),
    sa.Column('reg_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('marital_status', sa.String(), nullable=True),
    sa.Column('allergies', sa.String(), nullable=True),
    sa.Column('chronic_conditions', sa.String(), nullable=True),
    sa.Column('referred_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('shift', sa.String(), nullable=False),
    sa.Column('work_days', sa.String(), nullable=False),
    sa.Column('qualification', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('leave_balance', sa.Integer(), nullable=False),
    sa.Column('joining_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ambulance_trips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('caller_name', sa.String(), nullable=False),
    sa.Column('pickup_location', sa.String(), nullable=False),
    sa.Column('chief_complaint', sa.String(), nullable=False),
    sa.Column('urgency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('call_received', sa.DateTime(), nullable=False),
    sa.Column('handoff_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['ambulance_fleet.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('token', sa.Integer(), nullable=False),
    sa.Column('investigation_status', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['staff_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('gst', sa.Float(), nullable=False),
    sa.Column('insurance_cover', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payment_mode', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('blood_group', sa.String(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinical_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=True),
    sa.Column('doctor_name', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('s', sa.String(), nullable=True),
    sa.Column('o', sa.String(), nullable=True),
    sa.Column('a', sa.JSON(), nullable=False),
    sa.Column('p', sa.String(), nullable=True),
    sa.Column('signed', sa.Boolean(), nullable=False),
    sa.Column('signee', sa.String(), nullable=True),
    sa.Column('consent_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['staff_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinical_teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=False),
    sa.Column('leader_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leader_id'], ['staff_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diet_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('diet_type', sa.String(), nullable=False),
    sa.Column('preference', sa.String(), nullable=False),
    sa.Column('allergens', sa.JSON(), nullable=False),
    sa.Column('breakfast', sa.String(), nullable=False),
    sa.Column('lunch', sa.String(), nullable=False),
    sa.Column('dinner', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('icu_charting',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=True),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('rr', sa.Integer(), nullable=True),
    sa.Column('etco2', sa.Integer(), nullable=True),
    sa.Column('recorded_by', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investigations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('return_to_doctor', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('narcotics_register',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('drug_name', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('authorized_by', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ot_schedule',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room_number', sa.String(), nullable=False),
    sa.Column('procedure_name', sa.String(), nullable=False),
    sa.Column('surgeon_id', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['surgeon_id'], ['staff_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surgeries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('procedure_name', sa.String(), nullable=False),
    sa.Column('surgeon_id', sa.String(), nullable=True),
    sa.Column('anesthetist_id', sa.String(), nullable=True),
    sa.Column('room_number', sa.String(), nullable=False),
    sa.Column('scheduled_date', sa.String(), nullable=False),
    sa.Column('scheduled_time', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pre_op_checklist', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['anesthetist_id'], ['staff_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['surgeon_id'], ['staff_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vitals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('bp', sa.String(), nullable=True),
    sa.Column('temp', sa.String(), nullable=True),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('pulse', sa.Integer(), nullable=True),
    sa.Column('sugar', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ward_beds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ward_name', sa.String(), nullable=False),
    sa.Column('bed_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergency_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('triage_level', sa.String(), nullable=False),
    sa.Column('chief_complaint', sa.String(), nullable=False),
    sa.Column('brought_by', sa.String(), nullable=False),
    sa.Column('time_of_arrival', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('disposition', sa.String(), nullable=True),
    sa.Column('mlc_flag', sa.Boolean(), nullable=False),
    sa.Column('mlc_details', sa.JSON(), nullable=False),
    sa.Column('assigned_team_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_team_id'], ['clinical_teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_ward_admissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('bed_number', sa.String(), nullable=False),
    sa.Column('assigned_team_id', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_team_id'], ['clinical_teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('icu_admissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('bed_number', sa.String(), nullable=False),
    sa.Column('diagnosis', sa.String(), nullable=False),
    sa.Column('ventilator_status', sa.Boolean(), nullable=False),
    sa.Column('isolation_flag', sa.Boolean(), nullable=False),
    sa.Column('acuity_level', sa.String(), nullable=False),
    sa.Column('nurse_id', sa.String(), nullable=True),
    sa.Column('apache_score', sa.Float(), nullable=False),
    sa.Column('sofa_score', sa.Integer(), nullable=False),
    sa.Column('ews_score', sa.Integer(), nullable=False),
    sa.Column('assigned_team_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_team_id'], ['clinical_teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nurse_id'], ['staff_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clinical_record_id', sa.String(), nullable=False),
    sa.Column('medicines', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['clinical_record_id'], ['clinical_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('staff_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['clinical_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'staff_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_members')
    op.drop_table('prescriptions')
    op.drop_table('icu_admissions')
    op.drop_table('general_ward_admissions')
    op.drop_table('emergency_cases')
    op.drop_table('ward_beds')
    op.drop_table('vitals')
    op.drop_table('surgeries')
    op.drop_table('ot_schedule')
    op.drop_table('narcotics_register')
    op.drop_table('investigations')
    op.drop_table('icu_charting')
    op.drop_table('diet_orders')
    op.drop_table('clinical_teams')
    op.drop_table('clinical_records')
    op.drop_table('blood_requests')
    op.drop_table('billing_invoices')
    op.drop_table('appointments')
    op.drop_table('ambulance_trips')
    op.drop_table('staff_accounts')
    op.drop_table('patients')
    op.drop_table('notifications')
    op.drop_table('lab_reagents')
    op.drop_table('drug_inventory')
    op.drop_table('donors')
    op.drop_table('devices')
    op.drop_table('departments')
    op.drop_table('complaints')
    op.drop_table('blood_inventory')
    op.drop_table('audit_logs')
    op.drop_table('ambulance_fleet')
    # ### end Alembic commands ###
